CREATE TABLE urls (
    key TEXT PRIMARY KEY,
    url TEXT NOT NULL
);

CREATE TABLE stats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    time INTEGER NOT NULL
);

CREATE TABLE info (
    key TEXT PRIMARY KEY NOT NULL,
    value TEXT NOT NULL
);

INSERT INTO info VALUES ('version', '1');
